server:
  port: 8081
security:
  disable_cors: false
identity_provider:
  authorization_endpoint: https://auth.example.com/auth
  token_endpoint: https://auth.example.com/token
  end_session_endpoint: https://auth.example.com/logout
  circuit_breaker_timeout_ms: 30000
  auth_request_timeout_s: 600
application_configs:
  example-service:
    display_name: Example Service
    scope: example
    client_id: IAmNotSoSecret.
    client_secret: IAmVerySecret!
    default_redirect_url: https://example.com/app/
    redirect_url_pattern: https://example.com/app/(\?(foo=[a-z]+|bar=[0-9]{3,8}|&)+)?
