server:
  port: 8081
security:
  disable_cors: false
application_configs:
  room-service:
    display_name: Room Service
    authorization_endpoint: https://auth.eurofurence.example.com/auth
    scope: room
    client_id: IAmNotSoSecret.
    client_secret: IAmVerySecret!
    default_redirect_url: https://reg.eurofurence.example.com/room/
    code_challenge_method: S256
